name: wordpress_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.2.3+33

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.5
  dots_indicator: ^4.0.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^1.3.0
  jiffy: ^6.3.2
  path_provider: ^2.1.2
  provider: ^6.0.3
  shared_preferences: ^2.2.0
  skeleton_text: ^3.0.1
  firebase_core: ^3.13.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.2.4
  share_plus: ^10.1.4
  store_redirect: ^2.0.3
  package_info_plus: ^8.3.0
  easy_localization: ^3.0.3
  animated_bottom_navigation_bar: ^1.3.3
  flutter_web_browser: ^0.17.3
  fluttertoast: ^8.2.12
  google_mobile_ads: ^5.3.1
  loading_indicator: ^3.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_html_audio: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  firebase_analytics: ^11.4.4
  last_pod_player: ^0.0.5
  app_links: ^6.4.0
  timeago: ^3.6.1
  reading_time: ^2.0.0
  webview_flutter: ^4.10.0
  introduction_screen: ^3.1.17
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  firebase_auth: ^5.5.2
  carousel_slider_plus: ^7.0.0
  app_settings: 5.2.0
  onesignal_flutter: ^5.3.0
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  rounded_loading_button:
    git:
      url: https://github.com/scopendo/flutter_rounded_loading_button.git
      ref: master
  flare_flutter:
    git:
      url: https://github.com/mbfakourii/Flare-Flutter.git
      path: flare_flutter
      ref: remove_hashValues

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: "^0.14.3"



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

    

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
    - assets/animation_files/

  fonts:

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 400
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800


    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500




